"""Declarative base for all ORM models.

Defines the single :class:`Base` that every SQLAlchemy model in later phases
must inherit from. Concrete entity models are intentionally **not** defined
here (Phase 2.2 provides infrastructure only); this module exists so a single
:class:`sqlalchemy.MetaData` is shared across the codebase and picked up by
Alembic autogeneration.

A consistent naming convention is configured so that constraints and indexes
have deterministic names across environments, which keeps generated
migrations stable and reviewable.
"""

from __future__ import annotations

from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase

# Deterministic constraint/index naming (Alembic best practice). Keeps
# autogenerated migrations stable regardless of the backend defaults.
NAMING_CONVENTION: dict[str, str] = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base shared by all ORM models.

    All models inherit from this class so their tables register against a
    single metadata object. That metadata is the target for Alembic
    autogeneration.
    """

    metadata = MetaData(naming_convention=NAMING_CONVENTION)
