"""Add the user_profiles table for profile and preferences.

Revision ID: d490147de740
Revises: 50e72a6c0ded
Create Date: 2026-07-18 23:53:46.061478
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d490147de740"
down_revision: str | None = "50e72a6c0ded"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema changes for this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create pgcrypto extension if not exists (required for UUID generation)
    op.execute("CREATE EXTENSION IF NOT EXISTS \"pgcrypto\"")

    # Create base table with proper server-side defaults
    op.create_table(
        "user_profiles",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), nullable=False, unique=True),
        sa.Column("display_name", sa.String(length=255), nullable=False, server_default="New User"),
        sa.Column("avatar_url", sa.String(length=2048), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=False, server_default="UTC"),
        sa.Column("currency", sa.String(length=8), nullable=False, server_default="INR"),
        sa.Column("language", sa.String(length=8), nullable=False, server_default="en"),
        sa.Column("date_format", sa.String(length=16), nullable=False, server_default="DD/MM/YYYY"),
        sa.Column("theme", sa.String(length=16), nullable=False, server_default="system"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_profiles_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_profiles")),
    )

    # Add CHECK constraints after table creation (PostgreSQL requires this order).
    # Names match the MetaData naming_convention (ck_<table>_<name>) so they are
    # identical to what ``Base.metadata.create_all`` emits for the ORM model.
    op.execute("""
        ALTER TABLE user_profiles
        ADD CONSTRAINT ck_user_profiles_check_user_profiles_currency
        CHECK (currency IN ('INR', 'USD', 'EUR', 'GBP'));
    """)
    op.execute("""
        ALTER TABLE user_profiles
        ADD CONSTRAINT ck_user_profiles_check_user_profiles_theme
        CHECK (theme IN ('light', 'dark', 'system'));
    """)
    op.execute("""
        ALTER TABLE user_profiles
        ADD CONSTRAINT ck_user_profiles_check_user_profiles_language
        CHECK (language IN ('en', 'hi'));
    """)
    op.execute("""
        ALTER TABLE user_profiles
        ADD CONSTRAINT ck_user_profiles_check_user_profiles_date_format
        CHECK (date_format IN ('DD/MM/YYYY', 'MM/DD/YYYY', 'YYYY-MM-DD'));
    """)
    op.execute("""
        ALTER TABLE user_profiles
        ADD CONSTRAINT ck_user_profiles_check_user_profiles_non_empty_display_name
        CHECK (display_name != '');
    """)
    op.execute("""
        ALTER TABLE user_profiles
        ADD CONSTRAINT ck_user_profiles_check_user_profiles_valid_avatar_url
        CHECK (avatar_url IS NULL OR avatar_url LIKE 'http://%' OR avatar_url LIKE 'https://%');
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the schema changes for this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE user_profiles "
        "DROP CONSTRAINT ck_user_profiles_check_user_profiles_valid_avatar_url"
    )
    op.execute(
        "ALTER TABLE user_profiles "
        "DROP CONSTRAINT ck_user_profiles_check_user_profiles_non_empty_display_name"
    )
    op.execute(
        "ALTER TABLE user_profiles "
        "DROP CONSTRAINT ck_user_profiles_check_user_profiles_date_format"
    )
    op.execute(
        "ALTER TABLE user_profiles "
        "DROP CONSTRAINT ck_user_profiles_check_user_profiles_language"
    )
    op.execute(
        "ALTER TABLE user_profiles "
        "DROP CONSTRAINT ck_user_profiles_check_user_profiles_theme"
    )
    op.execute(
        "ALTER TABLE user_profiles "
        "DROP CONSTRAINT ck_user_profiles_check_user_profiles_currency"
    )
    op.drop_table("user_profiles")
    # The ix_user_profiles_user_id index is automatically created when a column is
    # declared unique=True, so there is no redundant index to drop.
